### Defining the matrix

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
x.shape

(2, 3)

In [4]:
np.random.randint(1,10,(2,3))

array([[1, 1, 8],
       [8, 8, 5]])

### Matrix Arithmetic

In [5]:
# Addition

np.random.seed(0)
a = np.random.randint(1,10,(2,3))
b = np.random.randint(11,20,(2,3))
print(a)
print(b)

[[6 1 4]
 [4 8 4]]
[[16 13 15]
 [18 17 19]]


In [6]:
a + b

array([[22, 14, 19],
       [22, 25, 23]])

In [7]:
# subtraction

a - b

array([[-10, -12, -11],
       [-14,  -9, -15]])

In [8]:
a

array([[6, 1, 4],
       [4, 8, 4]])

In [9]:
b

array([[16, 13, 15],
       [18, 17, 19]])

In [10]:
# multiplication - Hadamard

a * b

array([[ 96,  13,  60],
       [ 72, 136,  76]])

In [11]:
c = np.arange(1,3)
c

array([1, 2])

In [12]:
a + c

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [13]:
# matrix division

a / b

array([[0.375     , 0.07692308, 0.26666667],
       [0.22222222, 0.47058824, 0.21052632]])

### matrix multiplication - dot product

In [22]:

a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,2))
a

array([[9, 2],
       [7, 8]])

In [23]:
b

array([[8, 9],
       [2, 6]])

In [24]:
np.matmul(a,b)

array([[ 76,  93],
       [ 72, 111]])

In [27]:
a @ b

array([[ 76,  93],
       [ 72, 111]])

In [29]:
a.dot(b)

array([[ 76,  93],
       [ 72, 111]])

In [25]:
np.shape(a)

(2, 2)

In [26]:
np.shape(b)

(2, 2)

### Matrix Vector Multiplication

In [2]:
a = np.random.randint(10,100,(4,4))
a

array([[56, 32, 49, 30],
       [84, 35, 36, 75],
       [59, 71, 49, 56],
       [25, 87, 34, 44]])

In [4]:
b = np.arange(2,6)
b

array([2, 3, 4, 5])

In [5]:
c = a.dot(b)

In [6]:
c

array([554, 792, 807, 667])

### Matrix Scalar Multiplication

In [7]:
a

array([[56, 32, 49, 30],
       [84, 35, 36, 75],
       [59, 71, 49, 56],
       [25, 87, 34, 44]])

In [9]:
2 * a

array([[112,  64,  98,  60],
       [168,  70,  72, 150],
       [118, 142,  98, 112],
       [ 50, 174,  68,  88]])

### Types of matrix

In [13]:
# square matrix
# no.of rows = no.of columns

In [11]:
a

array([[56, 32, 49, 30],
       [84, 35, 36, 75],
       [59, 71, 49, 56],
       [25, 87, 34, 44]])

In [12]:
a.shape

(4, 4)

In [19]:
# symmetic matrix - is a type of square matrix where the top right triangle is same as bottom left triangle

In [15]:
a = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [2, 1, 2, 3, 4],
       [3, 2, 1, 2, 3],
       [4, 3, 2, 1, 2],
       [5, 4, 3, 2, 1]])

In [20]:
# Triangular Matrix - 2 types - is a type of square matrix

# upper triangular
# lower triangular


In [21]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [22]:
np.triu(a)

array([[1, 2, 3],
       [0, 2, 3],
       [0, 0, 3]])

In [23]:
np.tril(a)

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]])

In [24]:
# Diagonal Matrix - is a type of square matrix - 
# where all the diagonal elements are non - zero and all the non - diagonal elements are zero

In [26]:
d = np.array([[1,0,0],[0,2,0],[0,0,3]])
d

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [28]:
# identity matrix - is a type of diagonal matrix - all the principal diagonal elements is 1

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Matrix Operations

In [30]:
# Transpose

In [31]:
a = np.random.randint(10,100,(4,2))
a

array([[92, 21],
       [90, 36],
       [22, 82],
       [98, 18]])

In [32]:
b = a.T

In [33]:
b

array([[92, 90, 22, 98],
       [21, 36, 82, 18]])

In [34]:
# Determinant

In [35]:
x = np.random.randint(10,100,(4,4))
x

array([[80, 67, 51, 80],
       [18, 96, 51, 32],
       [81, 54, 52, 27],
       [59, 76, 73, 48]])

In [37]:
np.linalg.det(x)

6765225.000000006

In [38]:
# Rank of a matrix - no.of linearly independent rows or columns of a matrix

In [41]:
a

array([[92, 21],
       [90, 36],
       [22, 82],
       [98, 18]])

In [39]:
np.linalg.matrix_rank(a)

2

In [40]:
y = 2
np.linalg.matrix_rank(y)

1

In [42]:
x

array([[80, 67, 51, 80],
       [18, 96, 51, 32],
       [81, 54, 52, 27],
       [59, 76, 73, 48]])

In [43]:
np.linalg.matrix_rank(x)

4

In [44]:
b

array([[92, 90, 22, 98],
       [21, 36, 82, 18]])

In [45]:
np.linalg.matrix_rank(b)

2